---
collections:
  - name: community.general
  - name: netapp.ontap
  - name: hpe.ilo
  - name: ansible.windows
  - name: cloud.common
  - name: community.crypto
  - name: community.dns
  - name: community.docker
  - name: community.general
  - name: community.google
  - name: community.grafana
  - name: community.hashi_vault
  - name: community.hrobot
  - name: community.kubernetes
  - name: community.kubevirt
  - name: community.libvirt
  - name: community.mongodb
  - name: community.mysql
  - name: community.network
  - name: community.okd
  - name: community.postgresql
  - name: community.vmware
  - name: community.windows
  - name: community.zabbix
  - name: containers.podman
  - name: dellemc.enterprise_sonic
  - name: frr.frr
  - name: gluster.gluster
  - name: google.cloud
  - name: hetzner.hcloud
  - name: kubernetes.core
  - name: openstack.cloud
  - name: openvswitch.openvswitch
  - name: theforeman.foreman
  - name: vmware.vmware_rest
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.utils
  - name: cisco.ios
  - name: community.general
  - name: community.mysql
  - name: community.network
  - name: fedora.linux_system_roles
  - name: freeipa.ansible_freeipa
  - name: ovirt.ovirt
  - name: vyos.vyos
roles:
  - name: linux-system-roles.certificate
